[template]
# Name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "elasticsearch.yml.tmpl"

# The location to place the rendered configuration file
dest = "/esvol/config/elasticsearch.yml"

# The keys or directory to watch.  This is where the information to fill in the template will come from.
keys = [
    "/es/host",
    "/es/cluster",
]

# File ownership and mode information
owner = "elasticsearch"
mode = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
##check_cmd = "/usr/bin/supervisorctl elasticsearch check"
##reload_cmd = "/usr/bin/supervisorctl elasticsearch restart"
